
version: "3.8"
services:
  backend:
    build: ./backend/Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
